import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
//import { translate } from '@docusaurus/core';
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
/*
  tutorialSidebar: [
    'Create',
    {
      type: 'category',
      label: 'TEST1',
      items: ['Features/Create'],
    },
  ],
    */
};

export default {
  tutorialSidebar: [
    'tutorial',
    {
      type: 'category',
      label: 'Features',
      items: ['BackUp','Create', 'Devices', 'DevicesCatalogs', 'DevicesStorage', 'DevicesTree', 'Explore', 'Search', 'Selection', 'Settings', 'Statistics', 'Tags'],
    },
    {
      type: 'category',
      label: 'Development',
      items: ['Build-from-source', 'Code-structure', 'Roadmap'],
    },
  ],
};
