import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
//import { translate } from '@docusaurus/core';
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
/*
  tutorialSidebar: [
    'Create',
    {
      type: 'category',
      label: 'TEST1',
      items: ['Features/Create'],
    },
  ],
    */
};

export default {
  tutorialSidebar: [
    'Overview',
    'tutorial',
    {
      type: 'category',
      label: 'Features', //'Main Features (tabs)',
      items: [
                // {
                //   type: 'category',
                //   label: 'BackUp & Archiving',
                //   items: [
                'BackUp',
                //           'BackUp_luckybackup_profile',
                //   ],
                // },

                'Create',

                // {
                //   type: 'category',
                //   label: 'Devices',
                //   items: [
                    'Devices',
                    'DevicesTree',
                    'DevicesStorage',
                    'DevicesCatalogs',
                //   ],
                // },
                'Explore',
                'Search',
                'Selection',
                'Settings',
                'Statistics',
                'Tags',
                'CommandLines'
              ],
    },
    {
      type: 'category',
      label: 'Development',
      items: [  'Development-Overview',
                'Development-Roadmap',
                'Development-CodePractice',
      {
        type: 'category',
        label: 'Specifications',
        items: [
                'BackUp_luckybackup_profile',
                'DevicesCatalogChecksum',
                'DevicesCatalogMetadata',
                'SpecCatalogIncludeExclude',
                'SpecProgressReport',
                'SpecVersions',
                'SpecCollection',
                'SpecDeviceStorageRoot',
                'SpecDeviceActiveStatus',
                'SpecOperationQueue',
                'SpecSearchList',
                'SpecDevicesSplit',
                'SpecBackup'
                ],
      },
       'Development-Repository',
       'Development-Build-from-source',
       'Development-Release',
       'Development-Documentation'
              ],
    },
  ],
};
