title: Katalog Documentation
theme: jekyll-theme-primer
plugins:
  - jekyll-feed
  - jekyll-sitemap

baseurl: /Katalog
url: https://stephanecouturier.github.io

# Multilingual settings
lang: en
default_lang: en
localized_paths:
  cz: /cz/
  en: /en/
  fr: /fr/
